In [4]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [5]:
grades = np.array([85, 70, 90])

In [6]:
weights = np.array([0.3, 0.4, 0.3])

In [7]:
g = grades * weights
g

array([25.5, 28. , 27. ])

In [8]:
g.sum()

80.5

In [9]:
np.dot(grades, weights)   #內積dot()

80.5

In [10]:
grades = np.array([[85, 70, 90], [80, 60, 77], [75, 75, 90], [60, 70, 90]])
grades

array([[85, 70, 90],
       [80, 60, 77],
       [75, 75, 90],
       [60, 70, 90]])

In [11]:
weights = np.array([0.3, 0.4, 0.3])

In [13]:
all_grades = np.dot(grades, weights)
all_grades # 各自做dot()

array([80.5, 71.1, 79.5, 73. ])